#ifndef LIBFILEFIND_GLOBAL_H
#define LIBFILEFIND_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBFILEFIND_LIBRARY)
#  define LIBFILEFINDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBFILEFINDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBFILEFIND_GLOBAL_H
